# Generated by Django 4.2.8 on 2023-12-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("component_catalog", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="affected_by_vulnerabilities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="package",
            name="affected_by_vulnerabilities",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
